CrewManager/urls.py
from django.urls import path, include
from .views import CrewLV, CrewDV, CrewCV, CrewDelV, CrewUV, CrewJoin, crewlist_excel_export
from django.contrib.auth.decorators import login_required


app_name = 'crew'

urlpatterns = [
    path('', CrewLV.as_view(), name='list'),
    path('<int:pk>/', CrewDV.as_view(), name='detail'),
    path('new/', login_required(CrewCV.as_view()), name='new'),
    path('<int:pk>/delete/', login_required(CrewDelV.as_view()), name='delete'),
    path('<int:pk>/update/', login_required(CrewUV.as_view()), name='update'),
    path('<int:pk>/join/', login_required(CrewJoin), name='join'),

    path('data2excel/',crewlist_excel_export, name='data')

]

GWKS_CrewManager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from .views import IndexView
from django.conf.urls.static import static
from GWKS_CrewManager import settings

from ckeditor_uploader import views as ckeditor_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include(('accounts.urls','accounts'),namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    path('crew/', include(('CrewManager.urls','crew'),namespace='crew')),

    path('', IndexView.as_view(), name='index'),


    path('zoom/', include(('zoom.urls'),namespace='zoom')),
    # re_path('^ckeditor/', login_required(include('ckeditor_uploader.urls'))),
    re_path(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    re_path(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('apis/', include(('apis.urls'),namespace='apis')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_URL) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apis/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from .views import crew_list, crew_detail, user_list, user_detail, Kakao_Login, crew_join
#from .views import kakao_login, kakao_callback, KakaoLogin
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.permissions import AllowAny


app_name = 'apis'

schema_url_patterns = [
    path('/apis/crew/', crew_list),
    path('/apis/crew/<int:pk>/', crew_detail),
    path('/apis/crew/<int:pk>/join',crew_join),
    path('/apis/user/', user_list),
    path('/apis/user/<int:pk>/', user_detail),
    path('apis/accounts/',include('dj_rest_auth.urls')),
    path('apis/accounts/registration/',include('dj_rest_auth.registration.urls')),
    path('apis/accounts/kakao/',Kakao_Login.as_view()),
]
schema_view_v1 = get_schema_view(
    openapi.Info(
        title="Open API",
        default_version='v1',
        description="시스템 API",
        terms_of_service="https://www.google.com/policies/terms/",
    ),
    public=True,
    permission_classes=(AllowAny,),
    patterns=schema_url_patterns, )

urlpatterns = [
    path('crew/', crew_list),
    path('crew/<int:pk>/', crew_detail),
    path('crew/<int:pk>/join',crew_join),
    path('user/', user_list),
    path('user/<int:pk>/', user_detail),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_v1.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view_v1.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view_v1.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('accounts/',include('dj_rest_auth.urls')),
    path('accounts/registration/',include('dj_rest_auth.registration.urls')),

    path('accounts/kakao/',Kakao_Login.as_view()),
    #path('accounts/kakao',)
    #path('accounts/kakao/login/', kakao_login, name='kakao_login'),
    #path('accounts/kakao/login/callback/', kakao_callback, name='kakao_callback'),
    #path('accounts/kakao/login/finish/', KakaoLogin.as_view(), name='kakao_login_todjango'),

]

CrewManager/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User
from accounts.models import User
from django.utils.translation import gettext_lazy as _
from ckeditor_uploader.fields import RichTextUploadingField

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit

from multiselectfield import MultiSelectField



# Create your models here.
class Crew(models.Model):

    class MeetingType(models.TextChoices):
        ONLINE = '온라인', _('온라인')
        OFFLINE = '오프라인', _('오프라인')
        ON_OFFLINE = '온/오프라인', _('온/오프라인')

    # class CommunityType(models.TextChoices):
    #     FIRST = '1청년부', _('1청년부')
    #     SECOND = '2청년부', _('2청년부')
    #     THIRD = '3청년부', _('3청년부')
    #     MARRIED = '신혼브릿지', _('신혼브릿지')

    class WeekDayType(models.TextChoices):
        MONDAY = '월요일', _('월요일')
        TUESDAY = '화요일', _('화요일')
        WEDNESDAY = '수요일', _('수요일')
        THURSDAY = '목요일', _('목요일')
        FRIDAY = '금요일', _('금요일')
        SATURDAY = '토요일', _('토요일')
        SUNDAY = '일요일', _('일요일')
        NODAY = '선택안함', _('선택안함')

    class PeriodType(models.TextChoices):
        ONEWEEK = '매주', _('매주')
        TWOWEEK = '격주', _('격주')
        NOWEEK = '선택안함', _('선택안함')

    name = models.CharField('크루명 (30자 이내)', max_length=30)
    abstract = models.CharField('크루한줄설명 (30자 이내)', max_length=30)
    description = RichTextUploadingField('크루 설명 (모바일에 들어갈 사이즈입니다. 줄바꿈 확인필요, 이미지 업로드 가능)',blank=True, null=True)
    create_date = models.DateTimeField('크루 생성날짜', default=timezone.now)
    meeting_type = models.CharField('모임형태',max_length=6, choices=MeetingType.choices, default=MeetingType.ON_OFFLINE)

    meeting_time = models.CharField('기타 모임시간 (나중에 시간을 정해야한다면 여기다 적어주세요)',max_length=30)

    weekday = models.CharField('모임 요일', max_length=4, choices=WeekDayType.choices, default=WeekDayType.NODAY)
    period = models.CharField('모임 반복 주기', max_length=4, choices=PeriodType.choices, default=PeriodType.NOWEEK)
    start_time = models.TimeField('모임 시작 시간 (19:00 와 같은 형식으로 적어주세요)', blank=True, null=True)
    end_time = models.TimeField('모임 종료 시간 (21:00 와 같은 형식으로 적어주세요)', blank=True, null=True)



    meeting_limit = models.CharField('모임제한 (특별히 이런 사람들이 왔으면 좋겠다 같은 내용,30자 이내)',max_length=30)
    # community = models.CharField('크루 소속 공동체',max_length=6, choices=CommunityType.choices, default=CommunityType.FIRST)
    community = models.IntegerField('크루 소속 공동체 (크루리더가 소속된 공동체 = 예산사용공동체)', choices=User.CommunityType.choices, default=User.CommunityType.ETC)
    community_limit = MultiSelectField('크루원 참여 공동체 제한',choices=User.CommunityType.choices, null=True, blank=True)
    manager = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='크루매니저', related_name='manager')

    members = models.ManyToManyField(User,related_name='members')

    member_limit = models.PositiveSmallIntegerField("최대 모임 인원 (본인 포함)",default=5, help_text="5~15명 이내로 설정해주세요", validators=[MinValueValidator(5), MaxValueValidator(60)])
    image = ProcessedImageField(verbose_name='크루 소개 이미지 (정사각형, 500x500이상)',upload_to='crew/resize/%y%m%d',
                              processors=[ResizeToFit(width=500,height=500,upscale=False)],
                              format='JPEG', null=True, blank=True)
    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFit(width=200,height=200,upscale=False)],
                                                                 format='JPEG',
                                     options={'quality':60})

    kakao_room = models.URLField('오픈카톡방 URL',null=True, blank=True)


    class Meta:
        ordering = ['-id']

CrewManager/forms.py
from django import forms
from CrewManager.models import Crew
from accounts.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class CrewForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CrewForm,self).__init__(*args,**kwargs)
        if Crew.objects.filter(id=self.instance.id).exists():
            c = Crew.objects.filter(id=self.instance.id).get()
            self.fields['weekday'].initial = c.weekday
            self.fields['community_limit'].initial = c.community_limit

    weekday = forms.MultipleChoiceField(label="크루 모임 요일 (가능한 요일 하루만 선택해주세요)",choices=Crew.WeekDayType.choices, widget=forms.CheckboxSelectMultiple())
    community_limit = forms.MultipleChoiceField(label="크루 가입 가능 공동체 (가입가능공동체 모두 선택해주세요)",choices=User.CommunityType.choices, widget=forms.CheckboxSelectMultiple())

    def clean_weekday(self):
        if len(self.cleaned_data['weekday']) > 1:
            raise forms.ValidationError('한개 요일만 선택하세요.')
        return self.cleaned_data['weekday']

    def save(self, commit=True):
        crew = super().save(commit=False)
        crew.weekday = self.cleaned_data['weekday'][0]
        crew.community_limit = self.cleaned_data['community_limit']
        if commit:
            crew.save()
        return crew

    class Meta:
        model = Crew
        fields = \
            ['name','abstract', 'description', 'meeting_type',
             'community', 'member_limit','meeting_limit','image',
             'period', 'start_time','end_time','meeting_time', 'kakao_room'
             ]
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'abstract' : forms.TextInput(attrs={'class':'form-control'}),
            'meeting_time' : forms.TextInput(attrs={'class' : 'form-control'}),
            'meeting_limit' : forms.TextInput(attrs={'class' : 'form-control'}),
            'member_limit' : forms.NumberInput(),
            'start_time' : forms.TimeInput(attrs={'class':'form-control'}),
            'end_time' : forms.TimeInput(attrs={'class':'form-control'}),
            'kakao_room' : forms.URLInput(attrs={'class':'form-control'})
        }

CrewManager/views.py
import datetime
from io import BytesIO

import pandas as pd
from django.http import StreamingHttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.views.decorators import staff_member_required
from accounts.views import ManagerOnlyMixin

from CrewManager.models import Crew
from CrewManager.forms import CrewForm

from accounts.models import User

# Create your views here.
class CrewLV(ListView):
    model = Crew
    paginate_by = 10

class CrewDV(DetailView):
    model = Crew

class CrewCV(LoginRequiredMixin,CreateView):
    model = Crew
    form_class = CrewForm
    success_url = '/crew/'

    def form_valid(self, form):
        form.instance.manager = self.request.user
        form.instance.save()
        form.instance.members.add(self.request.user)

        return super().form_valid(form)

class CrewDelV(ManagerOnlyMixin,DeleteView):
    model = Crew
    success_url = '/crew/'

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class CrewUV(ManagerOnlyMixin,UpdateView):
    model = Crew
    form_class = CrewForm
    success_url = '/crew/'


def CrewJoin(request,pk):
    crew = get_object_or_404(Crew,pk=pk)
    if crew.members.count() >= crew.member_limit:
        return redirect('crew:detail', pk)
    else:
        u = User.objects.get(id=request.user.id)
        if crew.members.filter(id=request.user.id).exists() and crew.manager.id != request.user.id:
            crew.members.remove(request.user)
        elif crew.manager.id == request.user.id:
            pass
        elif not str(u.community) in crew.community_limit:
            pass
        else:
            crew.members.add(request.user)
        return redirect('crew:detail', pk)

@staff_member_required
def crewlist_excel_export(request):
    user = User.objects.all()

    data = []

    for u in user:
        d = {}
        d['이름'] = u.name
        d['소속'] = User.CommunityType.choices[u.community]
        d['이메일'] = u.email
        d['참여크루'] = [c.name for c in Crew.objects.filter(members__in=[u])]
        data.append(d)

    output = BytesIO()

    df = pd.DataFrame(data, columns=['이름', '소속', '이메일','참여크루'])

    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    df.to_excel(writer, sheet_name='Sheet1')
    writer.save()

    output.seek(0)
    # workbook = output.getvalue()
    date = datetime.datetime.now().strftime('%Y-%m-%d')
    response = StreamingHttpResponse(output,
                                     content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename=user_data_{date}.xlsx'
    return response

CrewManager/templates/CrewManager/crew_confirm_delete.html
{%  extends 'base.html' %}

{% block content %}
<div style="text-align: center; max-width:500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>삭제하시겠습니까?</h4>
    </div>
    <form action="{% url 'crew:delete' pk=object.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="확인">
    </form>
</div>

{% endblock %}

CrewManager/templates/CrewManager/crew_detail.html
{% extends 'base.html' %}

{% block content %}
    {% csrf_token %}
    <h2 class="border-bottom py-2">{{ object.name }}</h2>

    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line">
                {% if crew.image %}
                    <img src="{{ crew.image.url }}" class="shadow rounded" style="width:350px;height:350px"></img>
                {% endif %}
                <h4>{{ object.abstract }}</h4>
                <div class="card" style="width:350px">
                    <div class="card-body">
                        {{ object.description|safe }}
                    </div>
                </div>
                <H5>크루 정보</H5>
                <a> 크루모임형태 : {{ object.meeting_type }}</a>
                <a> 크루모임시간 : {% if object.period %}{{ object.period }} {% endif %}{% if object.weekday %}{{ object.weekday }} {% endif %}{% if object.start_time and object.end_time %} {{ object.start_time }} ~ {{ object.end_time }}{% endif %}</a>
                {% if not object.period %}
                    <a> 크루모임시간(기타) : {{ object.meeting_time }}</a>
                {% endif %}
                <a> 모임제한 : {{ object.meeting_limit }}</a>
                <a> 크루 소속 공동체 : {{ object.get_community_display }}</a>
                <a> 크루 가입가능 공동체 : {{ object.get_community_limit_display }}</a>
                <a> 크루 매니저 :
                <div class="d-inline-flex position-relative">
                    {% if crew.manager.profile_image %}
                        <img class="rounded shadow" src="{{ crew.manager.profile_image }}" alt="Avatar" style="width: 20px; height: 20px;">
                    {% endif %}
                        <p class="badge bg-primary">{{ crew.manager.name }}</p>
                </div>
                </a>
                <a> 크루 멤버 :{% for member in crew.members.all %}
                    <div class="d-inline-flex position-relative">
                    {% if member.profile_image %}
                        <img class="rounded shadow" src="{{ member.profile_image }}" alt="Avatar" style="width: 20px; height: 20px;">
                    {% endif %}
                        <p class="badge bg-primary">{{ member.name }}</p>
                        <p class="badge bg-primary">{{ member.email }}</p>
                    </div>
                </a>
                {% endfor %}
                {% if crew.kakao_room %}
                    <a href="{{ crew.kakao_room }}">크루 단톡방</a>
                {% endif %}
                <a> 최대모임인원 (본인 포함) : {{ crew.members.count }} / {{ crew.member_limit }}</a>
                <a> 크루생성날짜 : {{ object.create_date }}</a>


            </div>
        </div>
    </div>
    {% if user.id == crew.manager.id  %}
        <a href="{% url 'crew:delete' pk=object.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
        <a href="{% url 'crew:update' pk=object.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
    {% else %}
        {% if user in crew.members.all %}
            <a href="{% url 'crew:join' pk=object.id %}" class="btn btn-sm btn-outline-secondary">탈퇴</a>
        {% else %}
            <a href="{% url 'crew:join' pk=object.id %}" class="btn btn-sm btn-outline-secondary">등록</a>
        {% endif %}
    {% endif %}
{% endblock %}

CrewManager/templates/CrewManager/crew_form.html
{% extends 'base.html' %}
{% block extra-style %}
<style>
.cke_wysiwyg_frame{
  width: 350px!important;
}
</style>

{% endblock %}
{% block content %}
    <h5 class="my-3 border-bottom pb-2">크루 추가/수정</h5>
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
    {% include "form_errors.html" %}
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
{% endblock %}

CrewManager/templates/CrewManager/crew_list.html
{% extends 'base.html' %}
{% load Crew_filter %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="my-3">
            <a href="{% url 'crew:new' %}" class="create btn btn-sm btn-outline-secondary">추가</a>
        </div>
    {% endif %}

<table class="table">
    <thead class="table-light">
        <tr>
            <th>번호</th>
            <th>섬네일</th>
            <th>이름</th>
            <th>크루매니저</th>
            <th>멤버인원현황</th>
        </tr>
    </thead>
    <tbody>
    {% if page_obj %}
    {% for crew in page_obj %}
    <tr>
        <td>
            {{ page_obj.paginator.count|sub:page_obj.start_index|sub:forloop.counter0|add:1 }}
        </td>
        <td>
            {% if crew.image %}
            <img class="rounded shadow"src="{{ crew.image_thumbnail.url }}" style="width:50px;height:50px">
            {% endif %}
        </td>
        <td>
            <a href="{% url 'crew:detail' crew.id %}">{{ crew.name }}</a>
        </td>
        <td>
            <div class="d-inline-flex position-relative">
                {% if crew.manager.profile_image %}
                    <img class="rounded shadow" src="{{ crew.manager.profile_image }}" alt="Avatar" style="width: 20px; height: 20px;">
                {% endif %}
                    <p class="badge bg-primary">{{ crew.manager.name }}</p>
            </div>
        </td>
        <td>
            {{ crew.members.count }} / {{ crew.member_limit }}
        </td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">등록된 크루가 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
</table>
<ul class="pagination justify-content-center">
{% if page_obj.has_previous %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
</li>
{% else %}
<li class="page-item disabled">
    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
</li>
{% endif %}
{% for page_number in page_obj.paginator.page_range %}
    {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
        {%  if page_number == page_obj.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
    {% endif %}
{% endfor %}
{% if page_obj.has_next %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
</li>
{% else %}
<li class="page-item disabled">
    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
</li>
{% endif %}
</ul>

    {% if user.is_staff %}
        <a href="{% url 'crew:data' %}" class="btn btn-sm btn-outline-secondary">크루 데이터 엑셀 다운로드</a>
    {% endif %}
{% endblock %}

{% block footer %}
{%  endblock %}