GWKS_CrewManager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from .views import IndexView
from django.conf.urls.static import static
from GWKS_CrewManager import settings

from ckeditor_uploader import views as ckeditor_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include(('accounts.urls','accounts'),namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    path('crew/', include(('CrewManager.urls','crew'),namespace='crew')),

    path('', IndexView.as_view(), name='index'),


    path('zoom/', include(('zoom.urls'),namespace='zoom')),
    # re_path('^ckeditor/', login_required(include('ckeditor_uploader.urls'))),
    re_path(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    re_path(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('apis/', include(('apis.urls'),namespace='apis')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_URL) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apis/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from .views import crew_list, crew_detail, user_list, user_detail, Kakao_Login, crew_join
#from .views import kakao_login, kakao_callback, KakaoLogin
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.permissions import AllowAny


app_name = 'apis'

schema_url_patterns = [
    path('/apis/crew/', crew_list),
    path('/apis/crew/<int:pk>/', crew_detail),
    path('/apis/crew/<int:pk>/join',crew_join),
    path('/apis/user/', user_list),
    path('/apis/user/<int:pk>/', user_detail),
    path('apis/accounts/',include('dj_rest_auth.urls')),
    path('apis/accounts/registration/',include('dj_rest_auth.registration.urls')),
    path('apis/accounts/kakao/',Kakao_Login.as_view()),
]
schema_view_v1 = get_schema_view(
    openapi.Info(
        title="Open API",
        default_version='v1',
        description="시스템 API",
        terms_of_service="https://www.google.com/policies/terms/",
    ),
    public=True,
    permission_classes=(AllowAny,),
    patterns=schema_url_patterns, )

urlpatterns = [
    path('crew/', crew_list),
    path('crew/<int:pk>/', crew_detail),
    path('crew/<int:pk>/join',crew_join),
    path('user/', user_list),
    path('user/<int:pk>/', user_detail),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_v1.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view_v1.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view_v1.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('accounts/',include('dj_rest_auth.urls')),
    path('accounts/registration/',include('dj_rest_auth.registration.urls')),

    path('accounts/kakao/',Kakao_Login.as_view()),
    #path('accounts/kakao',)
    #path('accounts/kakao/login/', kakao_login, name='kakao_login'),
    #path('accounts/kakao/login/callback/', kakao_callback, name='kakao_callback'),
    #path('accounts/kakao/login/finish/', KakaoLogin.as_view(), name='kakao_login_todjango'),

]

zoom/urls.py
from django.urls import path
from .views import ZoomAccountLV, ZoomMeetingLV, getajaxlist, \
    ZoomMeetingDV, ZoomMeetingCV, ZoomMeetingDelV, ZoomMeetingUV

app_name = 'zoom'


urlpatterns = [
    path('account/',ZoomAccountLV.as_view(), name='accountlist'),

    path('meeting/',ZoomMeetingLV.as_view(), name='meetinglist'),
    path('meeting/getlist', getajaxlist, name='meetinglistupdate'),
    path('meeting/<int:pk>', ZoomMeetingDV.as_view(), name='meetingdetail'),
    path('meeting/new', ZoomMeetingCV.as_view(), name='meetingnew'),
    path('meeting/<int:pk>/delete', ZoomMeetingDelV.as_view(), name='meetingdelete'),
    path('meeting/<int:pk>/update', ZoomMeetingUV.as_view(), name='meetingupdate'),

]

zoom/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User

from django_jsonform.models.fields import JSONField

# Create your models here.

MEETING_TYPE_CHOICES = [
    (1, '일반'),
    (2, '예약'),
    (3, '반복'),
    (8, '반복예약')
]

SETTINGS_SCHEMA = {
    'type': 'dict',
    'keys': {
        'alternative_hosts': {
            'type': 'string',
            'title': '대체 호스트 지정',
            'format': 'email',
            'default': ''
        },
        "alternative_hosts_email_notification": {
            'type': 'boolean',
            'title': '대체 호스트 이메일 알림',
            'default': True
        },
        "breakout_room": {
            'type': 'dict',
            'title': '소회의실 설정',
            'keys': {
                "enable": {
                    'type': 'boolean',
                    'title': '소회의실 설정 여부',
                    'default': False
                },
                "rooms": {
                    'type': 'list',
                    'title': '소회의실 리스트',
                    'default': [],
                    'items': {
                        'type': 'dict',
                        'keys': {
                            'name': {
                                'type': 'string',
                                'title': '소회의실 이름',
                                'default': ''
                            },
                            'participants': {
                                'type': 'list',
                                'title': '소회의실 참석자 리스트',
                                'default': [],
                                'items': {
                                    'type': 'string',
                                    'default': '',
                                    'format': 'email'
                                }
                            }

                        }
                    }
                }
            }
        },
        "meeting_invitees": {
            'type': 'list',
            'title': '참석자 리스트',
            'default': [],
            'items': {
                'email': {
                    'type': 'string',
                    'title': '참석자 이메일',
                    'format': 'email',
                    'default': ''
                }
            }
        },
        "mute_upon_entry": {
            'type': 'boolean',
            'title': '입장시 음소거',
            'default': True
        },
        "participant_video": {
            'type': 'boolean',
            'title': '입장시 비디오 On',
            'default': True
        },
        "private_meeting": {
            'type': 'boolean',
            'title': '비공개 회의',
            'default': False
        },
        "waiting_room": {
            'type': 'boolean',
            'title': '대기실 On',
            'default': False
        }
    }
}


class ZoomAccount(models.Model):
    name = models.CharField('계정 이름', max_length=30)
    description = models.TextField('설명')
    create_date = models.DateTimeField('등록날짜', default=timezone.now)
    available = models.BooleanField('사용가능', default=False)
    appkey = models.CharField('키', max_length=30)
    secretkey = models.CharField('비밀 키', max_length=60)
    useremail = models.EmailField('사용자 이메일')

    def __str__(self):
        return self.name

class ZoomMeeting(models.Model):
    meetingid = models.IntegerField('id', default=0)
    topic = models.CharField('모임 주제',max_length=60)
    description = models.TextField('모임 설명', null=True, blank=True)
    type_meeting = models.PositiveSmallIntegerField('모임 타입', default=1, choices=MEETING_TYPE_CHOICES)
    create_dt = models.DateTimeField('등록날짜', default=timezone.now)
    start_dt = models.DateTimeField('시작시간',null=True, blank=True)
    duration = models.PositiveIntegerField('진행 시간')
    password = models.CharField('비밀번호', max_length=10, default='')
    join_url = models.URLField('모임 URL', default='')
    account = models.ForeignKey(ZoomAccount, on_delete=models.PROTECT, blank=True, null=True, verbose_name='줌 계정', related_name='account')
    user = models.ForeignKey(User, verbose_name='사용자', on_delete=models.PROTECT, blank=True, null=True)
    settings = JSONField(schema=SETTINGS_SCHEMA,null=True, blank=True)

    def __str__(self):
        return self.topic

zoom/forms.py
from django import forms
from .models import ZoomAccount, ZoomMeeting, MEETING_TYPE_CHOICES, SETTINGS_SCHEMA
from django.core.validators import MinValueValidator, MaxValueValidator
from django_jsonform.widgets import JSONFormWidget



class ZoomMeetingForm(forms.ModelForm):
    class Meta:
        model = ZoomMeeting
        fields = ['topic', 'description', 'type_meeting','start_dt', 'duration', 'account','settings']
        widgets = {
            'topic' : forms.TextInput(attrs={'class':'form-control'}),
            'description' : forms.Textarea(attrs={'class':'form-control', 'rows':5}),
            'type_meeting' : forms.Select(attrs={'class':'form-control'},choices=MEETING_TYPE_CHOICES),
            'start_dt' : forms.DateTimeInput(attrs={'class':'form-control'}),
            'duration' : forms.NumberInput(attrs={'class':'form-control'}),
            'account' : forms.Select(attrs={'class':'form-control'}),
            'settings': JSONFormWidget(schema=SETTINGS_SCHEMA)
        }

zoom/views.py
import datetime
import pytz

from django.utils import timezone
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from .models import ZoomAccount, ZoomMeeting
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin

import json
from .forms import ZoomMeetingForm
from .zoom import Zoom

# Create your views here.
class ZoomAccountDV(LoginRequiredMixin,DetailView):
    model = ZoomAccount
    template_name = 'zoom/zoomaccount_detail.html'


class ZoomAccountLV(LoginRequiredMixin,ListView):
    model = ZoomAccount
    template_name = 'zoom/zoomaccount_list.html'

class ZoomMeetingDV(DetailView):
    model = ZoomMeeting
    template_name = 'zoom/zoommeeting_detail.html'

class ZoomMeetingDelV(LoginRequiredMixin,DeleteView):
    model = ZoomMeeting
    template_name = 'zoom/zoommeeting_confirm_delete.html'
    success_url = '/zoom/meeting/'

class ZoomMeetingUV(LoginRequiredMixin,UpdateView):
    model = ZoomMeeting
    form_class = ZoomMeetingForm
    success_url = '/zoom/meeting/'

class ZoomMeetingCV(LoginRequiredMixin,CreateView):
    model = ZoomMeeting
    form_class = ZoomMeetingForm
    success_url = '/zoom/meeting/'

    def form_valid(self, form):
        self.object = form.save(commit=False)

        #여기에 추가로 저장할것 작성
        #self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class ZoomMeetingLV(ListView):
    model = ZoomMeeting
    template_name = 'zoom/zoommeeting_list.html'

    def get(self, request, *args, **kwargs):
        za = ZoomAccount.objects.filter(available=True)
        update_db(za)
        return super().get(request,*args,**kwargs)

def create_meeting(ZoomAccount, date, topic, duration, password):
    if ZoomAccount.available:
        zw = Zoom(ZoomAccount.appkey, ZoomAccount.secretkey, ZoomAccount.useremail)
        zw.CreateMeeting()


def update_db(ZoomAccount):
    for za in ZoomAccount:
        zm = ZoomMeeting.objects.filter(account=za)
        zw = Zoom(za.appkey, za.secretkey, za.useremail)
        zoom_list = zw.getlist()['meetings']
        for zl in zoom_list:
            if zm.filter(meetingid=zl['id']).exists():
                if zl['type'] == 8:
                    if not zm.filter(start_dt=zl['start_time']).exists():
                        data = ZoomMeeting(
                            meetingid=zl['id'],
                            topic=zl['topic'],
                            description='없음(줌 계정에서 생성)',
                            type_meeting=zl['type'],
                            create_dt=zl['created_at'],
                            duration=zl['duration'],
                            password='None',
                            join_url=zl['join_url'],
                            account=za
                        )
                        data.start_dt = zl['start_time']
                        data.save()
                    else:
                        pass
                else:
                    pass
            else:
                data = ZoomMeeting(
                    meetingid= zl['id'],
                    topic=zl['topic'],
                    description='없음(줌 계정에서 생성)',
                    type_meeting=zl['type'],
                    create_dt=zl['created_at'],
                    duration=zl['duration'],
                    password='None',
                    join_url=zl['join_url'],
                    account=za
                )
                if data.type_meeting != 3:
                    data.start_dt = zl['start_time']
                data.save()


def getajaxlist(request):
    KST = pytz.timezone('Asia/Seoul')
    datestr = list(request.GET.dict().keys())[0][:10]
    date_start = datetime.datetime.strptime(datestr,'%Y-%m-%d')
    zm = ZoomMeeting.objects.filter(start_dt__date = date_start.date())
    return_data = list()
    for d in zm:
        dict_data = {
            'id': d.meetingid,
            'name': d.topic,
            'start': d.start_dt.astimezone(KST).strftime("%Y-%m-%d %H:%M"),
            'end': (d.start_dt.astimezone(KST) + datetime.timedelta(minutes=d.duration)).strftime("%Y-%m-%d %H:%M"),
            'pk': d.id
        }
        return_data.append(dict_data)
    jsonObject = json.dumps(return_data)
    return HttpResponse(jsonObject,content_type="application/json")

zoom/templates/zoom/zoomaccount_list.html
{%  extends 'base.html' %}

{% block content %}

{% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-info">
</footer>
{% endblock %}

zoom/templates/zoom/zoommeeting_confirm_delete.html
<div style="text-align: center; max-width:500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>삭제하시겠습니까?</h4>
    </div>
    <form action="{% url 'zoom:meetingdelete' pk=object.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="확인">
    </form>
</div>

zoom/templates/zoom/zoommeeting_detail.html
<div class="card-text" style="white-space: pre-line">
    <a> 미팅 ID : {{ object.meetingid }}</a>
    <a> 모임 주제 : {{ object.topic }}</a>
    <a> 모임 설명 : {{ object.description }}</a>
    <a> 모임 타입 : {{ object.type_meeting }}</a>
    <a> 등록날짜 : {{ object.create_dt }}</a>
    <a> 시작시간 : {{ object.start_dt }}</a>
    <a> 진행시간 : {{ object.duration }}분</a>
    <a> 비밀번호: {{ object.password }}</a>
    <a> 모임 URL : {{ object.join_url }}</a>
    <a> 줌계정 : {{ object.account.name }} ({{ object.account.useremail }})</a>
    <a> 사용자 : {{ object.user.name }} ({{ object.user.email }})</a>
</div>
{% if user.id == object.user.id  %}
    <a href="{% url 'zoom:meetingdelete' pk=object.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
    <a href="{% url 'zoom:meetingupdate' pk=object.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
{% endif %}

zoom/templates/zoom/zoommeeting_form.html
<h5 class="my-3 border-bottom pb-2">미팅 생성</h5>
    <div class="card my-3">
        <div class="card-body">
            <form method="post" class="post-form my-3" id="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">등록</button>
            </form>
        </div>
</div>

<script type="text/javascript">

    $("#post-form").on('submit'), function(event){
    event.preventDefault();
    console.log("a");
    });

</script>

zoom/templates/zoom/zoommeeting_list.html
{%  extends 'base.html' %}
{% block extra-style %}
    {% load static %}

    <script src="{% static 'moment.js' %}"></script>
    <script src="{% static 'Snap.svg-0.5.1/dist/snap.svg.js' %}"></script>

    <script src={%  static 'frappe_gantt/gantt/dist/frappe-gantt.js' %}></script>
    <link rel="stylesheet" href="{%  static 'frappe_gantt/gantt/dist/frappe-gantt.css' %}">

    <script src={%  static 'datepicker/bootstrap-datepicker/dist/js/bootstrap-datepicker.js' %}></script>
    <link rel="stylesheet" href="{%  static 'datepicker/bootstrap-datepicker/dist/css/bootstrap-datepicker3.standalone.css' %}">

    <script src={% static 'django_jsonform/vendor/react.production.min.js' %}></script>
    <script src={% static 'django_jsonform/vendor/react-dom.production.min.js' %}></script>
    <script src={% static 'django_jsonform/react-json-form.min.js' %}></script>
{% endblock %}
{% block content %}

    <div class="card">
        <div class="card-body">
            <div>
                <a id="meetingnew" class="create btn btn-sm btn-outline-secondary">미팅 생성</a>
            </div>
            <div>
                <div id="datepicker" style="float:left">
                    <input type="hidden" id="selected_date">
                </div>
                <div>
                    <svg id="gantt"></svg>
                </div>
            </div>

        </div>
	</div>
    <div class="card">
        <div class="card-body">
            <div id="detail">

            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-info">
</footer>
{% endblock %}

{% block extra-script %}
    <script>


    let today = new Date();
    let tasks = [
        {% load zoom_tags %}
        {% for zm in object_list %}
            {% same_today zm.start_dt as ret %}
            {% if ret %}
            {
                id : "{{ zm.meetingid }}",
                name : "{{ zm.topic }}",
                start: "{{ zm.start_dt|date:"Y-m-d H:i"}}",
                end: "{{ zm.start_dt|add_hour:zm.duration|date:"Y-m-d H:i"}}",
                progress : 100,
                readonly : true,
                pk : {{ zm.id }},

            },
            {%  endif %}
        {% endfor %}

    ]

    var options = {
            header_height: 50,
            column_width: 30,
            step: 24,
            bar_height: 20,
            bar_corner_radius: 3,
            arrow_curve: 5,
            padding: 18,
            view_mode: 'Hour',
            date_format: 'YYYY-MM-DD',
            popup_trigger: 'click',
            custom_popup_html: null,
            language: 'ko',
            on_click: function (task)
            {
                $.ajax({
                    url : task.pk,
            headers : {
                'X-CSRFTOKEN' : '{{ csrf_token }}'
            },
            type : 'GET',
            success:function(data){
                $('#detail').html(data);
            },
            error: function() {
                $('#detail').html();
                }
            })
            }
        };



    if (tasks.length === 0)
    {
        tasks.push(
            {
            id : 'bundle',
            name : " ",
            start: today.toISOString().substring(0,10)+ " 00:00",
            end: today.toISOString().substring(0,10)+ " 01:00",
            progress : 100,
            readonly : true,
        }
        )
        var gantt = new Gantt("#gantt", tasks, options);
        $(".bar-wrapper[data-id='bundle']").remove(); // remove bar made by sample data
    }
    else
    {
        var gantt = new Gantt("#gantt", tasks, options);
    }



    $('#datepicker').datepicker({
    language: "ko",
    todayHighlight: true
    });


    $('#datepicker').on('changeDate', function() {
        let date = new Date($('#datepicker').datepicker('getFormattedDate'));
        tasks = []
        $.ajax({
            url : '{% url "zoom:meetinglistupdate" %}',
            headers : {
                'X-CSRFTOKEN' : '{{ csrf_token }}'
            },
            type : 'GET',
            data : date.toISOString(),
            success:function(data){

                for (const item of data)
                {
                    tasks.push(
                        {
                            id : item.id+"",
                            name : item.name,
                            start : item.start,
                            end : item.end,
                            progress : 100,
                            readonly : true,
                            pk : item.pk,
                        }
                    )
                }
                if (tasks.length === 0)
                {
                    tasks.push(
                        {
                        id : 'bundle',
                        name : " ",
                        start: date.toISOString().substring(0,10)+ " 00:00",
                        end: date.toISOString().substring(0,10)+ " 01:00",
                        progress : 100,
                        readonly : true,
                        }
                    )
                    gantt.refresh(tasks);
                    $(".bar-wrapper[data-id='bundle']").remove(); // remove bar made by sample data
                }
                else
                {
                    gantt.refresh(tasks);
                }
            },
            error: function() {
                tasks.push(
                {
                    id : 'bundle',
                    name : " ",
                    start: date.toISOString().substring(0,10)+ " 00:00",
                    end: date.toISOString().substring(0,10)+ " 01:00",
                    progress : 100,
                    readonly : true,
                });
                gantt.refresh(tasks);
                $(".bar-wrapper[data-id='bundle']").remove(); // remove bar made by sample data
                alert('error');
            }
        });
    });

    $('#meetingnew').on('click',function()
        {
            $.ajax({
                    url : 'new',
            headers : {
                'X-CSRFTOKEN' : '{{ csrf_token }}'
            },
            type : 'GET',
            success:function(data){
                $('#detail').html(data);
                let renewURL = location.href;
                if (!renewURL.endsWith('new')) {
                    renewURL += 'new'
                    history.pushState(null, null, renewURL)
                }
            },
            error: function() {
                $('#detail').html();

                }
            });
        });

    </script>

{% endblock %}