CrewManager/urls.py
from django.urls import path, include
from .views import CrewLV, CrewDV, CrewCV, CrewDelV, CrewUV, CrewJoin, crewlist_excel_export
from django.contrib.auth.decorators import login_required


app_name = 'crew'

urlpatterns = [
    path('', CrewLV.as_view(), name='list'),
    path('<int:pk>/', CrewDV.as_view(), name='detail'),
    path('new/', login_required(CrewCV.as_view()), name='new'),
    path('<int:pk>/delete/', login_required(CrewDelV.as_view()), name='delete'),
    path('<int:pk>/update/', login_required(CrewUV.as_view()), name='update'),
    path('<int:pk>/join/', login_required(CrewJoin), name='join'),

    path('data2excel/',crewlist_excel_export, name='data')

]

GWKS_CrewManager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from .views import IndexView
from django.conf.urls.static import static
from GWKS_CrewManager import settings

from ckeditor_uploader import views as ckeditor_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include(('accounts.urls','accounts'),namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    path('crew/', include(('CrewManager.urls','crew'),namespace='crew')),

    path('', IndexView.as_view(), name='index'),


    path('zoom/', include(('zoom.urls'),namespace='zoom')),
    # re_path('^ckeditor/', login_required(include('ckeditor_uploader.urls'))),
    re_path(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    re_path(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    path('apis/', include(('apis.urls'),namespace='apis')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_URL) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.views import UserCreateView, UserCreateDoneTV, UserLogout, UserLoginView



app_name = 'accounts'

urlpatterns = [
    path('login/', UserLoginView.as_view() , name='login'),
    path('logout/', UserLogout, name='logout'),

    path('register/', UserCreateView.as_view(), name='register'),
    path('register/done/', UserCreateDoneTV.as_view(), name='register_done'),


]

apis/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from .views import crew_list, crew_detail, user_list, user_detail, Kakao_Login, crew_join
#from .views import kakao_login, kakao_callback, KakaoLogin
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.permissions import AllowAny


app_name = 'apis'

schema_url_patterns = [
    path('/apis/crew/', crew_list),
    path('/apis/crew/<int:pk>/', crew_detail),
    path('/apis/crew/<int:pk>/join',crew_join),
    path('/apis/user/', user_list),
    path('/apis/user/<int:pk>/', user_detail),
    path('apis/accounts/',include('dj_rest_auth.urls')),
    path('apis/accounts/registration/',include('dj_rest_auth.registration.urls')),
    path('apis/accounts/kakao/',Kakao_Login.as_view()),
]
schema_view_v1 = get_schema_view(
    openapi.Info(
        title="Open API",
        default_version='v1',
        description="시스템 API",
        terms_of_service="https://www.google.com/policies/terms/",
    ),
    public=True,
    permission_classes=(AllowAny,),
    patterns=schema_url_patterns, )

urlpatterns = [
    path('crew/', crew_list),
    path('crew/<int:pk>/', crew_detail),
    path('crew/<int:pk>/join',crew_join),
    path('user/', user_list),
    path('user/<int:pk>/', user_detail),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_v1.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view_v1.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view_v1.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('accounts/',include('dj_rest_auth.urls')),
    path('accounts/registration/',include('dj_rest_auth.registration.urls')),

    path('accounts/kakao/',Kakao_Login.as_view()),
    #path('accounts/kakao',)
    #path('accounts/kakao/login/', kakao_login, name='kakao_login'),
    #path('accounts/kakao/login/callback/', kakao_callback, name='kakao_callback'),
    #path('accounts/kakao/login/finish/', KakaoLogin.as_view(), name='kakao_login_todjango'),

]

zoom/urls.py
from django.urls import path
from .views import ZoomAccountLV, ZoomMeetingLV, getajaxlist, \
    ZoomMeetingDV, ZoomMeetingCV, ZoomMeetingDelV, ZoomMeetingUV

app_name = 'zoom'


urlpatterns = [
    path('account/',ZoomAccountLV.as_view(), name='accountlist'),

    path('meeting/',ZoomMeetingLV.as_view(), name='meetinglist'),
    path('meeting/getlist', getajaxlist, name='meetinglistupdate'),
    path('meeting/<int:pk>', ZoomMeetingDV.as_view(), name='meetingdetail'),
    path('meeting/new', ZoomMeetingCV.as_view(), name='meetingnew'),
    path('meeting/<int:pk>/delete', ZoomMeetingDelV.as_view(), name='meetingdelete'),
    path('meeting/<int:pk>/update', ZoomMeetingUV.as_view(), name='meetingupdate'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="{% static 'bootstrap_5_1_3/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{%  static 'bootstrap_5_1_3/css/bootstrap.min.css' %}">

    <title>높은뜻 광성교회 청년마을 Crew</title>
    {% block extra-style %}
    {% endblock %}
</head>
<body style="padding-top:90px">
    {% include 'navbar.html' %}
    <div class="container my-3">
        {% block content %}
        {% endblock %}
    </div>

    {% block footer %}
    {% endblock %}


    {% block extra-script %}
    {% endblock %}

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/index.html
{% extends 'base.html' %}
{% block extra-style %}

{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
    <footer class="fixed-bottom bg-info">
    </footer>
{% endblock %}

{% block extra-script %}
{% endblock %}

templates/navbar.html
<div class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        {% load static %}
        <img href="{% url 'crew:list' %}" src="/media/GWKS_logo.png" style="width:40px; height:40px"/>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav align-items-center">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'crew:list' %}">크루 리스트</a>
                </li>


                {% if user.is_authenticated %}

{#                    <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'zoom:meetinglist' %}">줌 예약</a>#}
{#                    </li>#}
                    <li class="nav-item ">
                        <div class="d-inline-flex position-relative ">
                        {% if user.profile_image %}
                            <img class="rounded shadow" src="{{ user.profile_image }}" alt="Avatar" style="width: 20px; height: 20px;">
                        {% endif %}
                            <span class="badge bg-primary">{{ user.name }}</span>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                    {%  load socialaccount %}
                        <a href="{% provider_login_url "kakao" %}" class="nav-link" id="kakao_login">카카오로 로그인</a>
                    </li>
{#                    <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:register' %}">회원가입</a>#}
{#                    </li>#}
                {% endif %}

            </ul>
        </div>
    </div>
</div>